### ISSUE TITLE
Not receiving notifications 

### ISSUE THREAD

**Issue by nishantmendiratta** [pepalo/Safari-Push-Notifications-Heroku#1]
Using this repo and your doc i have successfully created a website - http://evening-spring-4637.herokuapp.com but it's not sending me any notifications need help a little bit.

**Comment by nishantmendiratta** [comment]
It's working now i just found that it's mandatory to use AUTHORISATION_CODE :) feeling awesome thanks a ton for creating this super beneficial repo. 

Regards
Nishant Mendiratta

**Comment by sojan-official** [comment]
@nishantmendiratta  glad to help :+1: 
all the best ..
