### ISSUE TITLE
I am having issue with this Please respond me

### ISSUE THREAD

**Issue by harsukhbir** [pepalo/Safari-Push-Notifications-Heroku#2]
openssl s_client -connect gateway.push.apple.com:2195 -CAfile apns-cert.pem
CONNECTED(00000003)
depth=1 /C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
verify error:num=20:unable to get local issuer certificate
verify return:0
773:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52.10.1/src/ssl/s23_lib.c:185:

**Comment by sojan-official** [comment]
are you running this on heroku  ? ( did you follow the steps in readme correctly ) ?
its seems like a ssl certificate error at your server. please check the configurations.

i have tested the code its working fine for me on heroku.

**Comment by harsukhbir** [comment]
Hi sojan,

Thanks for your response,

No I am not using heroku as I want to implement everything on my server. I getting response in console like : 

Object
body: "q"
button: "q"
test: 1
title: "q"
token: "53E27888E743075DD9A22BBEF3B276289AA4F3C31C41F74FA63B57A10715ACE0"
**proto**: Object

But not getting the notification on my safari.

Can you please help me 

Regards,

**Comment by harsukhbir** [comment]
@sojan-official  Can you please help me with this.
